### ISSUE TITLE
How to run a job?

### ISSUE THREAD

**Issue by ollieglass** [scrapinghub/python-scrapinghub#60]
I can't see how to run a job. There's two examples in the docs. In the project section:

```
For example, to schedule a spider run (it returns a job object):

>>> project.jobs.run('spider1', job_args={'arg1':'val1'})
<scrapinghub.client.Job at 0x106ee12e8>>

```

and in the spider section:

```
Like project instance, spider instance has jobs field to work with the spider's jobs.

To schedule a spider run:

>>> spider.jobs.run(job_args={'arg1:'val1'})
<scrapinghub.client.Job at 0x106ee12e8>>
```

Neither works, both throw `AttributeError: 'Jobs' object has no attribute 'run'`

**Comment by ollieglass** [comment]
Turns out the method is called `schedule`, not `run`

**Comment by jesuslosada** [comment]
Hi @ollieglass . It looks like you are using python-scrapinghub 1.9.0 (`schedule` is the right method in that version). You can read the documentation for that version here: 
https://github.com/scrapinghub/python-scrapinghub/tree/1.9.0
https://pypi.python.org/pypi/scrapinghub/1.9.0

The documentation in the master branch is currently being updated for the next major release (2.0.0).

**Comment by chekunkov** [comment]
Documentation is available via [Read The Docs](http://python-scrapinghub.readthedocs.io/en/stable/) now. Please install latest stable version from PyPI and try again @ollieglass, you were definitely using old version.

**Comment by ollieglass** [comment]
This was with scrapinghub 2.0.0.dev0

**Comment by chekunkov** [comment]
Right, that changed [here](https://github.com/scrapinghub/python-scrapinghub/pull/56) after 2.0.0.dev0 was released, and you saw docs from master branch. Sorry for the inconvenience, everything should be consistent now as we released a stable version.

**Comment by FM1337** [comment]
I'm getting the same error, I've upgraded to the latest version and it still doesn't work. What am I doing wrong?
